#!/usr/bin/env python3
import pathlib
import re

MODULUS = int(
    "0x1a0111ea397fe69a4b1ba7b6434bacd7"
    "64774b84f38512bf6730d2a0f6b0f624"
    "1eabfffeb153ffffb9feffffffffaaab",
    16,
)

R = pow(2, 384, MODULUS)
R_INV = pow(R, MODULUS - 2, MODULUS)


def limbs_from_int(x: int) -> list[int]:
    return [(x >> (64 * i)) & ((1 << 64) - 1) for i in range(6)]


def int_from_limbs(limbs: list[int]) -> int:
    return sum(l << (64 * i) for i, l in enumerate(limbs))


def mont_to_norm(x_mont: int) -> int:
    return (x_mont * R_INV) % MODULUS


def norm_to_mont(x: int) -> int:
    return (x * R) % MODULUS


def mont_mul(a: int, b: int) -> int:
    return (a * b * R_INV) % MODULUS


def mont_inv(a: int) -> int:
    # a is in Montgomery form; convert to normal, invert, and convert back.
    a_norm = mont_to_norm(a)
    inv_norm = pow(a_norm, MODULUS - 2, MODULUS)
    return norm_to_mont(inv_norm)


def parse_precomp_p(constants_path: pathlib.Path) -> tuple[int, int]:
    text = constants_path.read_text()
    m = re.search(
        r"var g1TatePrecompP = .*?X: fp.Element\{([^}]*)\},\s*Y: fp.Element\{([^}]*)\}",
        text,
        re.S,
    )
    if not m:
        raise RuntimeError("failed to parse g1TatePrecompP")
    x_limbs = [int(v.strip()) for v in m.group(1).split(",") if v.strip()]
    y_limbs = [int(v.strip()) for v in m.group(2).split(",") if v.strip()]
    x_mont = int_from_limbs(x_limbs)
    y_mont = int_from_limbs(y_limbs)
    return x_mont, y_mont


def build_ops_from_addchain() -> list[int]:
    # Derived from addchain.txt:
    # _10 = 2*1
    # _11 = 1 + _10
    # _1100 = _11 << 2
    # _1101 = 1 + _1100
    # _1101000 = _1101 << 3
    # _1101001 = 1 + _1101000
    # return ((_1101001 << 9 + 1) << 32 + 1) << 16
    ops: list[int] = []
    ops += [0] * 1  # 2*1
    ops += [1]      # +1
    ops += [0] * 2  # <<2
    ops += [1]      # +1
    ops += [0] * 3  # <<3
    ops += [1]      # +1
    ops += [0] * 9  # <<9
    ops += [1]      # +1
    ops += [0] * 32 # <<32
    ops += [1]      # +1
    ops += [0] * 16 # <<16
    return ops


def format_elem(x_mont: int) -> str:
    limbs = limbs_from_int(x_mont)
    return "{" + ", ".join(str(l) for l in limbs) + "}"


def main() -> None:
    repo_root = pathlib.Path(__file__).resolve().parents[2]
    constants_path = repo_root / "g1_tate_precomp_constants.go"
    xq, yq = parse_precomp_p(constants_path)

    ops = build_ops_from_addchain()

    tab: list[str] = []
    x_r, y_r = xq, yq
    three = norm_to_mont(3)
    two = norm_to_mont(2)
    for op in ops:
        if op == 0:
            lam = mont_mul(x_r, x_r)
            lam = mont_mul(three, lam)
            lam = mont_mul(lam, mont_inv(mont_mul(two, y_r)))
            x_next = (mont_mul(lam, lam) - (x_r + x_r)) % MODULUS
            y_next = (mont_mul(lam, (x_r - x_next) % MODULUS) - y_r) % MODULUS
        else:
            lam = mont_mul((y_r - yq) % MODULUS, mont_inv((x_r - xq) % MODULUS))
            x_next = (mont_mul(lam, lam) - x_r - xq) % MODULUS
            y_next = (mont_mul(lam, (x_r - x_next) % MODULUS) - y_r) % MODULUS

        tab.extend([format_elem(x_r), format_elem(y_r), format_elem(lam), format_elem(x_next)])
        x_r, y_r = x_next, y_next

    lines = []
    lines.append("// Code generated by cmd/g1tateprecompgen/main.py; DO NOT EDIT.")
    lines.append("package bls12381")
    lines.append("")
    lines.append("import (")
    lines.append("\tcurve \"github.com/consensys/gnark-crypto/ecc/bls12-381\"")
    lines.append("\t\"github.com/consensys/gnark-crypto/ecc/bls12-381/fp\"")
    lines.append(")")
    lines.append("")
    # Preserve existing g1TatePrecompP in Montgomery form.
    with constants_path.open() as f:
        text = f.read()
    m = re.search(r"var g1TatePrecompP = curve.G1Affine\{.*?\}\n", text, re.S)
    if not m:
        raise RuntimeError("failed to copy g1TatePrecompP")
    lines.append(m.group(0).rstrip())
    lines.append("")

    lines.append("var g1TatePrecompOps = []uint8{")
    lines.append("\t" + ", ".join(str(op) for op in ops) + ",")
    lines.append("}")
    lines.append("")

    lines.append("var g1TatePrecompTab = []fp.Element{")
    for i in range(0, len(tab), 4):
        lines.append("\t" + tab[i] + ",")
        lines.append("\t" + tab[i + 1] + ",")
        lines.append("\t" + tab[i + 2] + ",")
        lines.append("\t" + tab[i + 3] + ",")
    lines.append("}")
    lines.append("")

    constants_path.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
